name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What's Changed

  $CHANGES

  $CONTRIBUTORS

categories:
  - title: "Features"
    labels:
      - "feat"
  - title: "Fixes"
    labels:
      - "fix"
  - title: "Performance"
    labels:
      - "perf"
  - title: "Refactors"
    labels:
      - "refactor"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "Build & CI"
    labels:
      - "build"
      - "ci"
  - title: "Tests"
    labels:
      - "test"
  - title: "Chores"
    labels:
      - "chore"
  - title: "Other Changes"
    labels:
      - "other"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feat"
  patch:
    labels:
      - "fix"
      - "perf"
      - "refactor"
      - "docs"
      - "build"
      - "ci"
      - "test"
      - "chore"
      - "other"
  default: patch

autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?:/i'
  - label: "perf"
    title:
      - '/^perf(\(.+\))?:/i'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?:/i'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?:/i'
  - label: "build"
    title:
      - '/^build(\(.+\))?:/i'
  - label: "ci"
    title:
      - '/^ci(\(.+\))?:/i'
  - label: "test"
    title:
      - '/^test(\(.+\))?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?:/i'
  - label: "other"
    title:
      - '/.*/'
